name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sast_scan:
    name: Run Static Code and Container Image Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-code-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy SAST Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-code-results
          path: trivy-code-results.sarif

  image_scan:
    name: Build Image and Run Docker Scout and Trivy Image Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f Dockerfile -t pygoat_app:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.15.0
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PWD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif

      - name: Upload Docker Scout Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'pygoat_app:latest'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-results
          path: trivy-image-results.sarif
